flowchart TB
  title["F4: Token-local movements and shared-address links"]
  subgraph g0["Solana: 1111111111111112"]
  g0s["256294 movements; 39223 addresses"]
  g0a0["fUEc46T5acj5<br/>unclassified"]
  g0a1["1LGRatZJVidb<br/>unclassified"]
    g0a0 -->|3990| g0a1
  g0a2["BPd2hpNjYDjb<br/>unclassified"]
    g0a0 -->|3976| g0a2
  g0a3["qHHxdf56Cc7Q<br/>unclassified"]
  g0a4["u9Esa7hicLxZ<br/>unclassified"]
    g0a3 -->|1531| g0a4
  g0a5["Hh8ndUtqejY1<br/>unclassified"]
  g0a6["f6sBHm9295WY<br/>unclassified"]
    g0a5 -->|1344| g0a6
    g0a5 -->|1343| g0a2
  g0a7["xrvibsLPWuhd<br/>unclassified"]
  g0a8["5xB8PScLSr8i<br/>unclassified"]
    g0a7 -->|1276| g0a8
    g0a7 -->|1275| g0a2
  g0a9["qJgC226L1AsR<br/>unclassified"]
  g0a10["z2aTHLjU5daq<br/>unclassified"]
    g0a9 -->|1152| g0a10
  g0a11["p1ZrS8Sq5WD6<br/>unclassified"]
    g0a11 -->|693| g0a2
    g0a11 -->|693| g0a8
  g0a12["bSVmD9iX5vy7<br/>unclassified"]
    g0a12 -->|534| g0a2
    g0a0 -->|526| g0a6
  g0a13["Y2RYDrGLnuck<br/>unclassified"]
    g0a0 -->|512| g0a13
  g0a14["f11URpsC4i9D<br/>unclassified"]
    g0a0 -->|505| g0a14
  g0a15["9erNVbERnzXd<br/>unclassified"]
    g0a0 -->|504| g0a15
  g0a16["Ci9QoCnsZQug<br/>unclassified"]
    g0a0 -->|498| g0a16
    g0a0 -->|498| g0a8
  g0a17["H9WmKB48ULFY<br/>unclassified"]
    g0a0 -->|488| g0a17
    g0a12 -->|466| g0a8
  g0a18["8nEMKVZ9QoLp<br/>unclassified"]
    g0a0 -->|458| g0a18
  g0a19["4JpAmthxMZMc<br/>unclassified"]
    g0a19 -->|436| g0a2
    g0a19 -->|279| g0a8
  g0a20["89SiE33KVwcC<br/>unclassified"]
    g0a3 -->|218| g0a20
    g0a3 -->|211| g0a15
    g0a3 -->|209| g0a18
    g0a3 -->|202| g0a8
  g0a21["cbvjmFrhjWpx<br/>unclassified"]
    g0a3 -->|200| g0a21
    g0a3 -->|195| g0a17
  g0a22["59kRb2Fu6Je1<br/>unclassified"]
    g0a3 -->|195| g0a22
  g0a23["5MgBLyB3VUFW<br/>unclassified"]
    g0a3 -->|194| g0a23
  g0a24["naGLCEkXvjKS<br/>unclassified"]
    g0a3 -->|191| g0a24
    g0a3 -->|188| g0a14
    g0a3 -->|188| g0a13
  g0a25["hMGC5sGr8RbA<br/>unclassified"]
    g0a3 -->|186| g0a25
  g0a26["hsUStYbkj6Nn<br/>unclassified"]
    g0a3 -->|181| g0a26
    g0a3 -->|172| g0a16
    g0a3 -->|166| g0a2
    g0a3 -->|166| g0a6
  g0a27["55XQSzg6zDqP<br/>unclassified"]
    g0a27 -->|163| g0a20
    g0a27 -->|163| g0a2
    g0a27 -->|163| g0a8
  g0a28["VNte44amsWtz<br/>unclassified"]
  g0a29["FjNCZueVhBrw<br/>unclassified"]
    g0a28 -->|161| g0a29
    g0a9 -->|161| g0a17
    g0a9 -->|161| g0a23
    g0a9 -->|159| g0a26
    g0a9 -->|158| g0a13
    g0a27 -->|158| g0a22
    g0a9 -->|154| g0a6
    g0a27 -->|152| g0a17
    g0a9 -->|150| g0a21
    g0a9 -->|148| g0a20
    g0a9 -->|145| g0a25
    g0a9 -->|145| g0a8
    g0a9 -->|144| g0a15
    g0a9 -->|141| g0a2
    g0a9 -->|136| g0a16
    g0a9 -->|132| g0a22
    g0a9 -->|130| g0a18
    g0a19 -->|130| g0a16
    g0a9 -->|124| g0a14
    g0a9 -->|116| g0a24
    g0a27 -->|97| g0a13
    g0a12 -->|85| g0a16
    g0a27 -->|80| g0a6
    g0a27 -->|75| g0a14
    g0a19 -->|65| g0a18
    g0a27 -->|64| g0a16
    g0a12 -->|63| g0a22
    g0a27 -->|63| g0a15
    g0a27 -->|62| g0a18
    g0a19 -->|61| g0a22
    g0a27 -->|61| g0a26
    g0a12 -->|60| g0a13
    g0a27 -->|60| g0a25
    g0a27 -->|54| g0a24
    g0a12 -->|53| g0a23
    g0a19 -->|53| g0a13
    g0a27 -->|51| g0a23
    g0a27 -->|46| g0a21
    g0a12 -->|44| g0a14
    g0a12 -->|43| g0a26
    g0a19 -->|43| g0a25
    g0a12 -->|41| g0a18
    g0a12 -->|37| g0a6
    g0a19 -->|37| g0a6
    g0a19 -->|36| g0a17
    g0a12 -->|33| g0a15
    g0a19 -->|33| g0a24
    g0a19 -->|33| g0a26
    g0a12 -->|31| g0a21
    g0a19 -->|30| g0a15
    g0a12 -->|29| g0a17
    g0a19 -->|29| g0a14
    g0a28 -->|28| g0a16
    g0a28 -->|27| g0a14
    g0a12 -->|27| g0a25
    g0a12 -->|27| g0a24
    g0a28 -->|25| g0a20
    g0a28 -->|24| g0a18
    g0a28 -->|24| g0a23
    g0a28 -->|23| g0a24
    g0a28 -->|22| g0a13
    g0a28 -->|20| g0a22
    g0a28 -->|19| g0a21
    g0a28 -->|19| g0a15
    g0a19 -->|19| g0a20
    g0a28 -->|18| g0a26
    g0a12 -->|18| g0a20
    g0a19 -->|18| g0a21
    g0a28 -->|16| g0a2
    g0a28 -->|16| g0a25
    g0a19 -->|16| g0a23
    g0a28 -->|15| g0a8
    g0a28 -->|13| g0a17
    g0a28 -->|13| g0a6
    g0a0 -->|10| g0a22
    g0a5 -->|5| g0a23
    g0a5 -->|4| g0a14
    g0a5 -->|4| g0a21
    g0a5 -->|4| g0a16
    g0a5 -->|4| g0a15
    g0a5 -->|3| g0a22
    g0a5 -->|2| g0a25
    g0a5 -->|2| g0a13
    g0a5 -->|2| g0a26
    g0a5 -->|2| g0a8
    g0a5 -->|1| g0a20
    g0a5 -->|1| g0a24
    g0a5 -->|1| g0a18
    g0a7 -->|1| g0a25
    g0a11 -->|1| g0a18
    g0a11 -->|1| g0a26
    g0a0 -->|1| g0a20
    g0a0 -->|1| g0a25
    g0a0 -->|1| g0a24
    g0a0 -->|1| g0a26
  end
  title --- g0s
  subgraph g1["BSC: 035dbb4fe8324444"]
  g1s["8 movements; 8 addresses"]
  g1a0["ee9bcdaddddd<br/>unclassified"]
  g1a1["9f0b9550762b<br/>contract&#124;platform_contract"]
    g1a0 -->|1| g1a1
  g1a2["591551b59bd9<br/>unclassified"]
    g1a1 -->|1| g1a2
  g1a3["f520dcb09085<br/>unclassified"]
    g1a1 -->|1| g1a3
    g1a1 -->|1| g1a0
  g1a4["96cbcd8e9532<br/>unclassified"]
    g1a1 -->|1| g1a4
  g1a5["ab5ae4d24159<br/>unclassified"]
    g1a1 -->|1| g1a5
  g1a6["b105c127f89d<br/>unclassified"]
    g1a1 -->|1| g1a6
  g1a7["f53a1d8078ce<br/>unclassified"]
    g1a1 -->|1| g1a7
  end
  title --- g1s
  subgraph gog["Graph of graphs: up to ten platform-related tokens per chain"]
  token0["Solana: 1111111111111112"]
  token1["BSC: 035dbb4fe8324444"]
  token2["Solana: 8G4wEGGkZwyTDt1v"]
  token3["Solana: kY11McCe8BenwNYB"]
  token4["Solana: 7nBSPLjsLLW7pump"]
  token5["Solana: 5FiE5UE61vA1pump"]
  token6["Solana: cERj1RkCX58Hpump"]
  token7["Solana: JXFGttz3UAoVpump"]
  token8["Solana: DUuV8M3uyq5ppump"]
  token9["Solana: MGqWfcz2rsNzpump"]
  token10["Solana: R9knGDATw3sjpump"]
  token11["BSC: 9ca138411ae04444"]
  token12["BSC: 7f904150bc774444"]
  token13["BSC: dee6bbee3e704444"]
  token14["BSC: 0ced9b685be4ffff"]
  token15["BSC: 8e76b1b5d5e3ffff"]
  token16["BSC: 171df4c540d9ffff"]
  token17["BSC: 520f70968277ffff"]
  token18["BSC: a4c2b1d481f0ffff"]
  token19["BSC: e624ff6b247dffff"]
  end
  token1 -.-|shared 1; J 0.071| token11
  token1 -.-|shared 1; J 0.077| token12
  token1 -.-|shared 2; J 0.154| token13
  token1 -.-|shared 1; J 0.091| token14
  token1 -.-|shared 1; J 0.100| token15
  token1 -.-|shared 1; J 0.100| token16
  token1 -.-|shared 1; J 0.100| token17
  token1 -.-|shared 1; J 0.100| token18
  token1 -.-|shared 1; J 0.100| token19
  token11 -.-|shared 1; J 0.083| token12
  token11 -.-|shared 1; J 0.077| token13
  token11 -.-|shared 1; J 0.100| token14
  token11 -.-|shared 1; J 0.111| token15
  token11 -.-|shared 1; J 0.111| token16
  token11 -.-|shared 1; J 0.111| token17
  token11 -.-|shared 1; J 0.111| token18
  token11 -.-|shared 1; J 0.111| token19
  token12 -.-|shared 1; J 0.083| token13
  token12 -.-|shared 1; J 0.111| token14
  token12 -.-|shared 1; J 0.125| token15
  token12 -.-|shared 1; J 0.125| token16
  token12 -.-|shared 1; J 0.125| token17
  token12 -.-|shared 1; J 0.125| token18
  token12 -.-|shared 1; J 0.125| token19
  token13 -.-|shared 1; J 0.100| token14
  token13 -.-|shared 1; J 0.111| token15
  token13 -.-|shared 1; J 0.111| token16
  token13 -.-|shared 1; J 0.111| token17
  token13 -.-|shared 1; J 0.111| token18
  token13 -.-|shared 1; J 0.111| token19
  token14 -.-|shared 2; J 0.400| token15
  token14 -.-|shared 2; J 0.400| token16
  token14 -.-|shared 2; J 0.400| token17
  token14 -.-|shared 2; J 0.400| token18
  token14 -.-|shared 2; J 0.400| token19
  token15 -.-|shared 2; J 0.500| token16
  token15 -.-|shared 2; J 0.500| token17
  token15 -.-|shared 2; J 0.500| token18
  token15 -.-|shared 2; J 0.500| token19
  token16 -.-|shared 3; J 1.000| token17
  token16 -.-|shared 2; J 0.500| token18
  token16 -.-|shared 2; J 0.500| token19
  token17 -.-|shared 2; J 0.500| token18
  token17 -.-|shared 2; J 0.500| token19
  token18 -.-|shared 2; J 0.500| token19
  roles["Node roles are shown only when evidenced.<br/>Unverified pool/router roles stay unclassified.<br/>Solana token accounts are not projected to owners."]
  title --- roles
